[project]
name = "bmi-1-all-chat-bot"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.49.0",
    "openai>=1.68.2",
    "python-dotenv>=1.1.0",
    "python-telegram-bot>=22.0",
]
